import turtle
from time import sleep

turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.setheading(0)
turtle.forward(20)
sleep(0.5)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.setheading(90)
turtle.forward(20)
sleep(0.5)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.setheading(180)
turtle.forward(20)
sleep(0.5)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.setheading(-90)
turtle.forward(20)
sleep(0.5)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()

turtle.done()